### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by hzeng-otterai** [galsang/BIMPM-pytorch#4]
Hi, Thanks for converting the model to pytorch. But I always got memory error by using this tool, I checked one of the existing issues and set the --max-sent-len to 32. But still got the same error. What else can I try to solve it?

```
$ python train.py --data-type Quora --max-sent-len 32
loading Quora data...
100%|████████████████████████████████████████████████████████████████████████████| 2196017/2196017 [02:21<00:00, 15546.98it/s]
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    main()
  File "train.py", line 127, in main
    data = Quora(args)
  File "/home/vba/dev/external/BIMPM-pytorch/model/utils.py", line 70, in __init__
    self.TEXT.build_vocab(self.train, self.dev, self.test, vectors=GloVe(name='840B', dim=300))
  File "/home/vba/anaconda3/lib/python3.6/site-packages/torchtext/vocab.py", line 347, in __init__
    super(GloVe, self).__init__(name, url=url, **kwargs)
  File "/home/vba/anaconda3/lib/python3.6/site-packages/torchtext/vocab.py", line 236, in __init__
    self.cache(name, cache, url=url)
  File "/home/vba/anaconda3/lib/python3.6/site-packages/torchtext/vocab.py", line 327, in cache
    self.vectors = torch.Tensor(vectors).view(-1, dim)
MemoryError

```

**Comment by galsang** [comment]
Which GPU are you using? I've tried with TitanXp. 

> --num-perspective NUM_PERSPECTIVE

 is the most important factor for memory utilization, so you can try to decrease it. (with performance degradation).
In fact, the model itself is quite memory-heavy though more optimization would be needed.

**Comment by hzeng-otterai** [comment]
I am using a 1080 Ti. 

I just changed GloVe vector name to '42B' and the training is running now. I think it's because my memory is only 16G so using 840B caused error in vocabulary building.

**Comment by hzeng-otterai** [comment]
With the GloVe vector name as '42B', I can finish the training as below.
`python train.py --data-type Quora`

But after 10 epoch of training, the testing accuracy is around 81.5%. The 42B GloVe won't cause such a big difference right? What are the parameters you use to achieve 87.3%? @galsang 

Thanks!

**Comment by galsang** [comment]
As I remember, I used the parameters which are set as default in the code.
Different word embeddings can lead to different results.

**Comment by hzeng-otterai** [comment]
Oh, right, 840B embedding is case sensitive and 42B is case insensitive, so the results are very different.

Thanks for the great code!
